### ISSUE TITLE
Melhorar seções html 

### ISSUE THREAD

**Issue by AbraaoAlves** [osvaldolimah/osvaldolimah.github.io#1]
Você pode usar a [tag section](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/section#exemplo_1) ao invés de apenas a div 

https://github.com/osvaldolimah/osvaldolimah.github.io/blob/d3209dffc2d0249f6d0e96e3d125c970ac68a663/index.html#L11C6-L11C9

``` suggestion 
   <section >
````

**Comment by osvaldolimah** [comment]
Obrigado pelo feedback @AbraaoAlves . Farei a substituição.
